name: renovate
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: renovatebot/github-action@v39.1.4
      with:
        configurationFile: .github/renovate.json
        token: ${{ secrets.RENOVATE_TOKEN }}
