name: "build"
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: renovatebot/github-action@v39.1.3
      with:
        configurationFile: .github/renovate.json
        token: ${{ secrets.RENOVATE_TOKEN }}
