name: renovate
permissions: write-all
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: renovatebot/github-action@v41.0.5
      with:
        configurationFile: .github/renovate.json
        token: ${{ secrets.RENOVATE_TOKEN }}
